### ISSUE TITLE
Bspwm parpadea

### ISSUE THREAD

**Issue by Sheep3017** [ZLCube/AutoBspwm#1]
Cada vez despues de un rato en la terminal, el entorno “parpadea” o más bien aparecen dos rayas horizontales negras al ritmo que presiono las teclas, mientras escribo apareces estas dos rayas muy molestas y si alguien tiene una solucion lo agradecería enormemente

Pd: el rofi tampoco me carga el tema seleccionado, y dice que no existe “selector.rasi”

**Comment by devaacode** [comment]
Buenas, tengo 2 problemas, el primero es que despues de instalar todo y poner los wallpapers el teclado se pone en ingles y no puedo cambiarlo de ninguna manera, lo cambio y sigue en ingles y segundo instale el tema de pacman y se ve lageado todo y no me funciona el menu de inicio.

**Comment by ZLCube** [comment]
Probablemente sea el motor de renderizado, el picom es el que se encarga de esto, lo puedes contrar en ~/.config/picom/picom.conf, en la parte inferior de general settings encontraras que hay una opción de renderizado con la variable de nombre backend y el valor glx el cual es el motor de renderizado "backend = "glx";" dado a que cada maquina tiene especificaciones diferentes te recomendaría probar cambiando glx por xrender", espero esto te sirva de utilidad
