### ISSUE TITLE
Pregunta 

### ISSUE THREAD

**Issue by Fereck** [ZLCube/AutoBspwm#3]
Como puedo usar la barra de "Target" ?

**Comment by Pentest4noob** [comment]
en la terminal escribe settarget + ip de la maquina
y para limpiarlo solo escribe settarget y presiona enter

**Comment by IsDerky** [comment]
El tema de Legion esta disponible? Ya que al seleccionarlo y abrir el BSPWM se queda congelado con el fondo del login de Kali

**Comment by ZLCube** [comment]
Lanzaré una actualización para Legion proximamente
