### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by santiagomac** [ZLCube/AutoBspwm#4]
Al momento de instalar el tema los bordes no se acomodan y aparecen en negro:
![image](https://github.com/ZLCube/AutoBspwm/assets/80358248/cd9ddec2-0358-4556-9116-7bc555298a2b)

**Comment by ZLCube** [comment]
Probablemente sea el motor de renderizado, el picom es el que se encarga de esto, lo puedes contrar en ~/.config/picom/picom.conf, en la parte inferior de general settings encontraras que hay una opción de renderizado con la variable de nombre backend y el valor glx el cual es el motor de renderizado "backend = "glx";" dado a que cada maquina tiene especificaciones diferentes te recomendaría probar cambiando glx por xrender", espero esto te sirva de utilidad
