### ISSUE TITLE
Problemas con instalación

### ISSUE THREAD

**Issue by Javiergmz** [ZLCube/AutoBspwm#5]
Buenas, tengo problemas con la instalación, estoy instalando la ultima versión de kali y cuando ejecuto el script, no me llega a salir la ventana para elegir theme, y se cierra automaticamente la shell dejando el vim abierto con que ya puedo elegir theme, he intentado hacerlo 3 veces y lo mismo, a ver si alguien me puede echar un cable.

Gracias de antemano.

**Comment by ZLCube** [comment]
El selector de temas utiliza la herramienta zenity, misma que aparentemente en las nuevas versiones de kali no viene instalada por defecto, debes correr el comando "sudo apt install zenity" y después reintentar la instalación, lanzaré un parche pronto sin embargo espero te sirva de utilidad por el momento.
