### ISSUE TITLE
settarget no funciona

### ISSUE THREAD

**Issue by ssanjua** [ZLCube/AutoBspwm#6]
hola cube, no se si este es un problema solo mio pero no consigo colocar el target.

settarget "trump 29.2.92.9"
settarget:2: no such file or directory: /root/.config/bin/target

estoy en una vmware corriendo Kali Linux.

**Comment by ZLCube** [comment]
Estás como root, el target se encuentra en ~/.config/bin/target por lo que
necesitar usar el usuario kali para definirlo, por otro lado no hace falta
que coloques comillas, puedes correr el comando settarget trump 29.2.92.9
sin problemas

**Comment by ssanjua** [comment]
Listo, no tenia permisos de ejecucion mi user. 
Gracias por todo.
