### ISSUE TITLE
problemas con target

### ISSUE THREAD

**Issue by SDLV98** [ZLCube/AutoBspwm#7]
Hola! settarget con el usuario de kali no me funcionaba, pero editando directamente el archivo target me ha dejado meter la IP.

Mi duda es, para cambiarla por otra ip cómo se hace? En el archivo no lo pude reescribir, me salía vacío.

Muchas gracias!!

**Comment by ssanjua** [comment]
hola! para poder usarlo lo que hice fue darle permisos con mi usuario porque solo los tenia con root en .config/bin/target 
y para resetear el target, si pones settarget vacio, se resetea.
espero te sirva.

**Comment by SDLV98** [comment]
holaa de nuevo, pues probé a darle permisos y nada... yo creo que será algún bug porque el settarget nunca me llegó a funcionar vaya.. Y muchas gracias! :)

te dejo por aqui lo último que intente, que fue sobreescribir una vez cambie permisos, sobreescribir me deja pero no se muestra la ip cambiada 
![imagen_2024-08-28_130025364](https://github.com/user-attachments/assets/84b49b8a-1189-43cb-bb64-83d75b80bf12)

**Comment by ZLCube** [comment]
Hola, aquí tienes una solución definitiva:

1. Sal de modo root, asegúrate de que seas usuario kali
2. En el directorio ~/.config/ Crea una carpeta llamada bin2: `mkdir ~/.config/bin2/`
3. Copia el contenido de los scripts de carpeta bin a la carpeta bin2, asegúrate de que ningún archivo se cree como root
4. Elimina la carpeta bin y mueve la carpeta bin2: `rm -rf ~/.config/bin` `sudo mv ~/.config/bin2 ~/.config/bin`
5. Asigna permisos de ejecucion a los scripts: `chmod +x htb_status` etc...

De esa manera te aseguras de que ningun script ni archivo tiene privilegios de root y cualquier usuario puede acceder a ellos y modificarlos, para cambiar el target unicamente tienes que usar el comando `settarget valor_que_quieras` o `settarget` para limpiarlo

**Comment by SDLV98** [comment]
Muchísimas gracias, ha quedado solucionado.

Y perdón por las molestias!!

**Comment by AdrianCE94** [comment]
Buenas, hice los pasos creando carpeta bien2 borrando renombrando y demás y cuando hago set target ip nombre no se cambia gráficamente el target ni en /etc/hosts aparece nada.

**Comment by AdrianCE94** [comment]
<img width="1887" height="302" alt="Image" src="https://github.com/user-attachments/assets/ad762963-c58c-4a00-8089-8e0224075664" />
