### ISSUE TITLE
Script bugeado

### ISSUE THREAD

**Issue by Engpro6** [ZLCube/AutoBspwm#8]
Estoy en kali linux. El script de auto_install.sh no para de dar los dos mismos problemas: si lo ejecuto como usuario no root me pide la contraseña para sudo, la doy bien, y empieza a printearse muchas veces el banner del principio, y eligiendo bien la opcion de kali. Si lo ejecuto como root, me da el error que sale cuando un proceso de apt está intentando ejecutarse cuando otro ya se está ejecutando (Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 11259 (apt)) Por favor, solucionad este error

**Comment by ZLCube** [comment]
El script no se debe ejecutar como root, el seleccionar el tema tiene que hacerse al finalizar el script y tienes que actualizar tu sistema operativo antes de ejecutar el install.

**Comment by Engpro6** [comment]
El sistema ya lo actualizo antes de cada ejecución, y no me sale el theme selector

**Comment by ZLCube** [comment]
puedes ejecutar manualmente el install.sh y luego el theme.sh, recuerda seguir el paso a paso del video en youtube y no debería darte ningún problema si lo sigues al pie de la letra

**Comment by Engpro6** [comment]
Al ejecutar el theme.sh, me deja elegir el tema legion me aparece aparece el selector del tema de rofi, elijo el tema y me cierra sesión. Al intentar iniciar el bspwm se queda pillado el login
