### ISSUE TITLE
Fuente en la terminal no se muestra correctamente

### ISSUE THREAD

**Issue by s7lver2** [ZLCube/AutoBspwm#9]
Hola, acabo de instalar tus configuraciones con el script y me ha sucedido esto
![image](https://github.com/user-attachments/assets/2468dad2-6d6d-44c8-8d5d-1c9590e43ba4)
uso virtualbox, si necesitas otras especificaciones, las puedo pasar

adjunto mas imagenes
![image](https://github.com/user-attachments/assets/3f7ea4ed-5c95-405f-848d-54bd5d27b008)

**Comment by ZLCube** [comment]
El entorno está optimizado para funcionar en VMWare, cualquier otro hipervisor podría dar problemas con el renderizado o el compositor en este caso picom, podrías tratar de cambiar el renderizado dentro del archivo ~/.config/picom/picon.conf y remplzar glx por xrender más no te aseguro que solucione el problema, espero este aproach te funcione.  

```
##############################################################################
#                                    GENERAL                                 #
##############################################################################

# Daemonize process. Fork to background after initialization. Causes issues with certain (badly-written) drivers.
# daemon = false

# Specify the backend to use: xrender, glx, or xr_glx_hybrid.
# xrender is the default one.
#
# backend = 'glx'
backend = "glx"; #aqui remplaza glx por xrender
```
